[buildPlans.IosevkaHomemade]
family = "Iosevka Homemade"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaHomemade.variants.design]
one = "no-base-flat-top-serif"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
zero = "tall-slashed-cutout"
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hookless"
capital-i = "serifless"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-n = "asymmetric-serifless"
capital-q = "horizontal-tailed"
capital-r = "standing-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "flat-hook-serifless"
g = "single-storey-earless-rounded"
i = "serifless"
j = "flat-hook-serifless"
k = "straight-serifless"
l = "semi-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-corner-serifless"
s = "serifless"
t = "hookless-asymmetric-short-neck2"
u = "toothless-rounded-serifless"
v = "straight-serifless"
w = "straight-vertical-sides-serifless"
x = "cursive"
y = "cursive-serifed"
z = "straight-serifless-with-horizontal-crossbar"
cyrl-capital-er = "closed-serifless"
cyrl-er = "earless-rounded-serifless"
braille-dot = "square"
tilde = "high"
asterisk = "turn-hex-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-open-tall"
ampersand = "upper-open"
at = "threefold-solid-inner"
dollar = "open"
cent = "open"
percent = "dots"
bar = "force-upright"
question = "smooth"
pilcrow = "low"
partial-derivative = "straight-bar"
micro-sign = "toothless-rounded-serifless"

[buildPlans.IosevkaHomemade.variants.italic]
one = "no-base-flat-top-serif"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
eight = "two-circles"
nine = "closed-contour"
zero = "tall-slashed-cutout"
capital-b = "more-asymmetric-serifless"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hookless"
capital-i = "serifless"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-n = "asymmetric-serifless"
capital-q = "horizontal-tailed"
capital-r = "standing-serifless"
a = "double-storey-serifless"
b = "toothed-serifed"
c = "unilateral-serifed"
d = "toothed-serifed"
e = "rounded"
f = "flat-hook-diagonal-tailed-crossbar-at-x-height"
g = "double-storey"
i = "tailed"
j = "diagonal-tailed-serifed"
k = "diagonal-tailed-cursive-serifless"
l = "tailed-serifed"
m = "serifless"
n = "tailed-serifless"
p = "eared-serifed"
q = "diagonal-tailed-motion-serifed"
r = "serifed"
s = "unilateral-serifed"
t = "diagonal-tailed-asymmetric-short-neck2"
u = "toothed-serifed"
v = "cursive-serifed"
w = "cursive-serifed"
x = "cursive"
y = "cursive-serifed"
z = "cursive-with-horizontal-crossbar"
lower-lambda = "curly-tailed-turn"
lower-mu = "toothed-serifed"
lower-chi = "chancery"
cyrl-capital-zhe = "cursive"
cyrl-zhe = "cursive"
cyrl-capital-ze = "bilateral-inward-serifed"
cyrl-ze = "bilateral-inward-serifed"
cyrl-capital-ka = "symmetric-connected-serifed"
cyrl-ka = "symmetric-connected-serifed"
cyrl-el = "tailed"
cyrl-em = "slanted-sides-flat-bottom-serifed"
cyrl-capital-en = "serifed"
cyrl-en = "tailed-serifed"
cyrl-capital-er = "closed-serifless"
cyrl-er = "earless-rounded-serifless"
braille-dot = "square"
tilde = "high"
asterisk = "turn-hex-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-open-tall"
ampersand = "upper-open"
at = "threefold-solid-inner"
dollar = "open"
cent = "open"
percent = "dots"
bar = "force-upright"
question = "smooth"
pilcrow = "low"
partial-derivative = "straight-bar"
micro-sign = "toothless-rounded-serifless"

  [buildPlans.IosevkaHomemade.ligations]
  inherits = "dlig"
