# • remove all double spaces
# • remove system field
# • remove all instances of double colon followed by space
# • add an "[" and "]" and remove ":" in lines with a word followed by ":"

name = "Black Metal (Dark Funeral)"
slug = "black-metal-dark-funeral"
author = "metalelf0 (https://github.com/metalelf0)"
variant = "dark"
[palette]
  base00 = "000000"
  base01 = "121212"
  base02 = "222222"
  base03 = "333333"
  base04 = "999999"
  base05 = "c1c1c1"
  base06 = "999999"
  base07 = "c1c1c1"
  base08 = "5f8787"
  base09 = "aaaaaa"
  base0A = "5f81a5"
  base0B = "d0dfee"
  base0C = "aaaaaa"
  base0D = "888888"
  base0E = "999999"
  base0F = "444444"

