# • remove all double spaces
# • remove system field
# • remove all instances of double colon followed by space
# • add an "[" and "]" and remove ":" in lines with a word followed by ":"

author = "guy"
name = "blueberry"
slug = "blueberry"
[palette]
base00 = "14131d"
base01 = "343051"
base02 = "3b3854"
base03 = "343051"
base04 = "7b7bbb"
base05 = "b8b8ff"
base06 = "b8b8ff"
base07 = "0b091d"
base08 = "ff8888" 
base09 = "ffa588"
base0A = "fffdd0"
base0B = "88ff88"
base0C = "88ffff"
base0D = "bbbbff"
base0E = "e7c5ff"
base0F = "b8b8ff"
