## Plugin loader
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

## Options
# Fix contrast issues
face global      MenuForeground       black,blue
face global      MenuBackground      black,white
face global    PrimarySelection    black,blue+fg
face global  SecondarySelection   black,green+fg

## Plugins and features
# Indentation
plug "andreyorst/smarttab.kak" defer %{
    set global indentwidth 4
    set global softtabstop 4
}

hook global BufOpenFile .* expandtab
hook global BufNewFile  .* expandtab

# LSP
eval %sh{kak-lsp}
lsp-enable

lsp-inlay-hints-enable global
lsp-inlay-diagnostics-enable global

set global lsp_hover_max_diagnostic_lines 5
set global lsp_snippet_support true

# Lua Scripting
plug "gustavo-hms/luar" %{
    require-module luar
}

# Language Support
source "%val{config}/load/notes.kak"
